research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

writing_task:
  description: >
    Using the blog_plan and research_output provided, create an engaging and comprehensive blog post about {topic}.
    Ensure to:
    - Follow the structure outlined in the blog_plan
    - Incorporate key findings from the research_output
    - Maintain a balance between technical accuracy and readability
    - Include proper attribution for sources and expert insights
    - Apply SEO best practices in content structure
  expected_output: >
    A complete, publication-ready blog post formatted in markdown without '```',
    including headers, subheaders, and properly formatted links and citations.
  agent: writer

review_task:
  description: >
    Conduct a thorough review of the blog post, analyzing:
    - Alignment with original blog_plan
    - Accurate representation of research_output
    - Technical accuracy and depth
    - Content structure and flow
    - SEO optimization
    - Writing quality and engagement
    - Citation and attribution accuracy
  expected_output: >
    A detailed review report containing:
    - Overall assessment
    - Section-by-section analysis
    - Specific improvement recommendations
    - Technical accuracy verification
    - SEO optimization suggestions
    - Writing style feedback
    Formatted as markdown without '```'
  agent: quality_reviewer
